version: "3.3"
services:
  redis:
    # 镜像及版本      
    image: redis:6.2.6
    # 自定义容器名
    container_name: redis
    # docker启动时,自动启动该容器
    restart: ${RESTART_POLICY}
    # 挂载映射，可以让数据或配置持久化
    volumes:
      # <本地配置文件> : <docker中的配置文件> : <ro:docker容器对该文件只读,默认是rw可读可写>
      - ${PWD}/redis_data/redis.conf:/etc/redis/redis.conf:ro
      # <本地数据目录> : <docker中的数据目录>
      - ${PWD}/redis_data/data:/data
      # <本地日志目录> : <docker中的日志目录>
      # redis不具有自动创建/logs的权限，如果redis.conf中指定的相对位置,则数据目录已经可以映射出日志文件
      #- ../redis/logs:/logs
    # docker执行的启动命令
    command: redis-server /etc/redis/redis.conf
    ports:
     # <本地端口> : <docker容器端口>
     - 6378:6379
         # 日誌配置
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
